export const globalInitialState = {
  isAuthUser: false,
  flag: true,
  bookmarkFlag: false,
  carTypeData: {
    carType: [],
    loading: false,
  },
  carBrandData: {
    carBrand: [],
    loading: false,
  },
  carOwnershipData: {
    carOwnership: [],
    loading: false,
  },
  carFuelTypeData: {
    carFuelType: [],
    loading: false,
  },
  carModelData: {
    carModel: [],
    loading: false,
  },
  carBudgetRange: [20, 80],
  buyCarDetails: {
    buyCar: [],
    loading: false,
  },
  userDetails: null,
  carOwnerShip: ["1st Owner", "2nd Owner"],
  carFuelType: ["Petrol", "Diesel", "CNG"],
  carRegState: [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  ],
};
